<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("title", "Обзоры");
$APPLICATION->SetTitle("Обзоры");
?><?$APPLICATION->IncludeComponent(
	"bitrix:news",
	"landings_block",
	Array(
		"ADD_DETAIL_TO_SLIDER" => "Y",
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_PICT_PROP" => "MORE_PHOTO",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"AJAX_FILTER_CATALOG" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"ALT_TITLE_GET" => "NORMAL",
		"BG_POSITION" => "top left",
		"BLOCK_BLOG_NAME" => "Статьи",
		"BLOCK_BRANDS_NAME" => "Бренды",
		"BLOCK_LANDINGS_NAME" => "Коллекции",
		"BLOCK_NEWS_NAME" => "Новости",
		"BLOCK_PARTNERS_NAME" => "Партнеры",
		"BLOCK_PROJECTS_NAME" => "Проекты",
		"BLOCK_REVIEWS_NAME" => "Отзывы",
		"BLOCK_SERVICES_NAME" => "Услуги",
		"BLOCK_STAFF_NAME" => "Сотрудники",
		"BLOCK_TIZERS_NAME" => "",
		"BLOCK_VACANCY_NAME" => "Вакансии",
		"BLOG_TITLE" => "Комментарии",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "N",
		"CACHE_TIME" => "100000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"COMMENTS_COUNT" => "5",
		"COMPONENT_TEMPLATE" => "landings_block",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"CONVERT_CURRENCY" => "N",
		"COUNT_IN_LINE" => "3",
		"DEFAULT_LIST_TEMPLATE" => "block",
		"DEPTH_LEVEL_BRAND" => "2",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_BLOCKS_ALL_ORDER" => "tizers,preview_text,char,docs,services,news,vacancy,blog,projects,brands,staff,gallery,partners,form_order,landings,reviews,goods_sections,goods,goods_catalog,desc,comments",
		"DETAIL_BLOG_EMAIL_NOTIFY" => "N",
		"DETAIL_BLOG_URL" => "catalog_comments",
		"DETAIL_BLOG_USE" => "Y",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FB_USE" => "N",
		"DETAIL_FIELD_CODE" => array(0=>"NAME",1=>"PREVIEW_TEXT",2=>"PREVIEW_PICTURE",3=>"DETAIL_TEXT",4=>"DETAIL_PICTURE",5=>"",),
		"DETAIL_LINKED_GOODS_SLIDER" => "Y",
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => array(0=>"LINK_BRANDS",1=>"LINK_VACANCY",2=>"LINK_LANDINGS",3=>"LINK_NEWS",4=>"LINK_REVIEWS",5=>"LINK_PARTNERS",6=>"LINK_PROJECTS",7=>"LINK_STAFF",8=>"LINK_BLOG",9=>"LINK_TIZERS",10=>"LINK_SERVICES",11=>"SITE",12=>"PHONE",13=>"DOCUMENTS",14=>"PHOTOS",15=>"SIDE_IMAGE",16=>"",),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DETAIL_USE_COMMENTS" => "N",
		"DETAIL_VK_USE" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_COMPARE" => "Y",
		"DISPLAY_NAME" => "N",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_WISH_BUTTONS" => "Y",
		"ELEMENT_TYPE_VIEW" => "element_1",
		"FILE_404" => "",
		"GALLERY_PRODUCTS_PROPERTY" => "PHOTOS",
		"GALLERY_TYPE" => "small",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"HIDE_NOT_AVAILABLE" => "N",
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"IBLOCK_CATALOG_ID" => "26",
		"IBLOCK_CATALOG_TYPE" => "-",
		"IBLOCK_ID" => "18",
		"IBLOCK_LINK_BLOG_ID" => "17",
		"IBLOCK_LINK_BRANDS_ID" => "30",
		"IBLOCK_LINK_LANDINGS_ID" => "17",
		"IBLOCK_LINK_NEWS_ID" => "20",
		"IBLOCK_LINK_PARTNERS_ID" => "23",
		"IBLOCK_LINK_PROJECTS_ID" => "15",
		"IBLOCK_LINK_REVIEWS_ID" => "19",
		"IBLOCK_LINK_SERVICES_ID" => "22",
		"IBLOCK_LINK_STAFF_ID" => "16",
		"IBLOCK_LINK_TIZERS_ID" => "10",
		"IBLOCK_LINK_VACANCY_ID" => "2",
		"IBLOCK_TYPE" => "aspro_max_content",
		"IMAGE_POSITION" => "left",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"LINKED_ELEMENST_PAGE_COUNT" => "20",
		"LINKED_PRODUCTS_PROPERTY" => "BRAND",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(0=>"NAME",1=>"PREVIEW_TEXT",2=>"PREVIEW_PICTURE",3=>"",),
		"LIST_OFFERS_FIELD_CODE" => array(0=>"",1=>"",),
		"LIST_OFFERS_LIMIT" => "5",
		"LIST_OFFERS_PROPERTY_CODE" => array(0=>"SIZES3",1=>"SIZES4",2=>"SIZES5",3=>"SIZES",4=>"COLOR_REF",5=>"",),
		"LIST_PROPERTY_CATALOG_CODE" => array(0=>"",1=>"",),
		"LIST_PROPERTY_CODE" => array(0=>"",1=>"SITE",2=>"PHONE",3=>"",),
		"LIST_VIEW" => "slider",
		"MAX_GALLERY_GOODS_ITEMS" => "5",
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "20",
		"NUM_DAYS" => "30",
		"NUM_NEWS" => "20",
		"OFFERS_CART_PROPERTIES" => array(),
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_ORDER2" => "desc",
		"OFFER_ADD_PICT_PROP" => "MORE_PHOTO",
		"OFFER_HIDE_NAME_PROPS" => "N",
		"OFFER_TREE_PROPS" => array(0=>"SIZES3",1=>"SIZES4",2=>"SIZES5",),
		"ONLY_ELEMENT_DISPLAY_VARIANT" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Новости",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PREVIEW_TRUNCATE_LEN" => "300",
		"PRICE_CODE" => array(0=>"BASE",1=>"OPT",2=>"",),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_PROPERTIES" => array(),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"SALE_STIKER" => "-",
		"SECTION_ELEMENTS_TYPE_VIEW" => "list_elements_1",
		"SEF_FOLDER" => "/landings/",
		"SEF_MODE" => "Y",
		"SEF_URL_TEMPLATES" => array("news"=>"","section"=>"","detail"=>"#ELEMENT_CODE#/","rss"=>"rss/","rss_section"=>"#SECTION_ID#/rss/",),
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "N",
		"SHOW_404" => "Y",
		"SHOW_ARTICLE_SKU" => "N",
		"SHOW_COUNT_ELEMENTS" => "Y",
		"SHOW_DETAIL_LINK" => "Y",
		"SHOW_DISCOUNT_PERCENT" => "N",
		"SHOW_DISCOUNT_PERCENT_NUMBER" => "N",
		"SHOW_DISCOUNT_TIME" => "Y",
		"SHOW_DISCOUNT_TIME_EACH_SKU" => "N",
		"SHOW_GALLERY" => "Y",
		"SHOW_GALLERY_GOODS" => "Y",
		"SHOW_ICONS_SECTION" => "N",
		"SHOW_LINKED_PRODUCTS" => "Y",
		"SHOW_MEASURE" => "N",
		"SHOW_MEASURE_WITH_RATIO" => "N",
		"SHOW_OLD_PRICE" => "N",
		"SHOW_ONE_CLICK_BUY" => "Y",
		"SHOW_RATING" => "Y",
		"SHOW_SECTION_PREVIEW_DESCRIPTION" => "Y",
		"SHOW_UNABLE_SKU_PROPS" => "Y",
		"SIDE_LEFT_BLOCK" => "FROM_MODULE",
		"SIDE_LEFT_BLOCK_DETAIL" => "FROM_MODULE",
		"SIZE_IN_ROW" => "4",
		"SORT_BUTTONS" => array(0=>"POPULARITY",1=>"NAME",2=>"PRICE",),
		"SORT_BY1" => "SORT",
		"SORT_BY2" => "ID",
		"SORT_ORDER1" => "ASC",
		"SORT_ORDER2" => "DESC",
		"SORT_PRICES" => "REGION_PRICE",
		"SORT_REGION_PRICE" => "BASE",
		"STAFF_TYPE_DETAIL" => "list",
		"STIKERS_PROP" => "-",
		"STORES" => array(0=>"1",1=>"",),
		"STRICT_SECTION_CHECK" => "N",
		"TYPE_LEFT_BLOCK" => "FROM_MODULE",
		"TYPE_LEFT_BLOCK_DETAIL" => "FROM_MODULE",
		"T_DOCS" => "",
		"T_GALLERY" => "Галерея",
		"T_GOODS" => "",
		"T_GOODS_SECTION" => "",
		"T_PROJECTS" => "",
		"T_REVIEWS" => "",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"USE_PERMISSIONS" => "N",
		"USE_PRICE_COUNT" => "N",
		"USE_RATING" => "N",
		"USE_REVIEW" => "N",
		"USE_RSS" => "Y",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "Y",
		"USE_SUBSCRIBE_IN_TOP" => "N",
		"VIEW_TYPE" => "table",
		"YANDEX" => "N"
	)
);?> <br>
 
<div style="display: flex; flex-wrap: wrap; justify-content: center; align-items: center; gap: 25px; row-gap: 20px;">
	 <!-- Логотип 2GIS -->
	<div style="display: inline-flex; align-items: center; justify-content: center; transition: transform 0.2s ease, opacity 0.2s ease;">
 <a target="_blank" href="https://2gis.ru/vladivostok/firm/3518965489879088" style="text-decoration: none;"> <img width="140" alt="logo_2gis.jpg" src="/upload/medialibrary/93c/ykmm7xy0zclgyp5fek4v45wcy8r891m7.jpg" height="44" title="logo_2gis.jpg" style="height: auto; max-width: 100%; display: block; width: 140px;"> </a>
	</div>
	 <!-- Логотип Яндекс -->
	<div style="display: inline-flex; align-items: center; justify-content: center; transition: transform 0.2s ease, opacity 0.2s ease;">
 <a target="_blank" href="https://yandex.com/maps/org/tafi/1051051202/?ll=131.894836%2C43.137875&z=16" style="text-decoration: none;"> <img width="257" alt="logo_яндекс.png" src="/upload/medialibrary/52b/z2ogm1suovdchixsty3j12k3zypm0psm.png" height="44" title="logo_яндекс.png" style="height: auto; max-width: 100%; display: block; width: 257px;"> </a>
	</div>
	 <!-- Логотип ПроДокторов -->
	<div style="display: inline-flex; align-items: center; justify-content: center; transition: transform 0.2s ease, opacity 0.2s ease;">
 <a target="_blank" href="https://prodoctorov.ru/vladivostok/lpu/59406-tafi-diagnostika/" style="text-decoration: none;"> <img width="350" alt="logo_prodoktorov.png" src="/upload/medialibrary/3ca/u23pvbntmik1uem5y04owd61o2eecoi1.png" height="44" title="logo_prodoktorov.png" style="height: auto; max-width: 100%; display: block; width: 350px;"> </a>
	</div>
</div>
 <br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>