<div class="allergolog-block fifth">
    <img src="/images/allergolog-3.png" alt="allergolog">
    <div>
        <h2>Как подготовиться к исследованию?</h2>
        <p>
            Кровь рекомендуется сдавать на голодный желудок, в утреннее время, так как в течение дня показатели могут
            значительно колебаться, и утренние результаты считаются наиболее надежными.
        </p>
        <p>
            Отмена антигистаминных препаратов не требуется.
        </p>
        <p>
            За сутки до анализа необходимо исключить алкоголь и избегать интенсивных физических нагрузок.
        </p>
        <p>
            Лучше всего накануне исследования поужинать легкой и нежирной пищей.
            За 15 минут до взятия крови рекомендуется избегать нагрузок: посидеть в лаборатории, восстановить
            дыхание и успокоиться.
        </p>
        <p>
            Если у вас обострение хронического заболевание, назначены дополнительные медикаменты, о правилах подготовки
            лучше проконсультироваться с вашим лучащим врачом.
        </p>
    </div>
</div>

<?php if (!empty($arParams['ELEMENTS'])): ?>
    <div class="tickborne__second">
      <?
      $APPLICATION->IncludeComponent(
        "bitrix:catalog.section",
        'tick_borne',
        Array(
          "COMPATIBLE_MODE" => "Y",
          "USE_REGION" => "N",
          "STORES" => array(),
          "SHOW_BIG_BLOCK" => "N",
          "IS_CATALOG_PAGE" => "Y",
          "SHOW_UNABLE_SKU_PROPS" => "N",
          "ALT_TITLE_GET" => "NORMAL",
          "SEF_URL_TEMPLATES" => array(
            "sections" => "",
            "section" => "#SECTION_CODE_PATH#/",
            "element" => "#SECTION_CODE_PATH#/#ELEMENT_CODE#/",
            "compare" => "compare.php?action=#ACTION_CODE#",
            "smart_filter" => "#SECTION_CODE_PATH#/filter/#SMART_FILTER_PATH#/apply/",
          ),
          "IBLOCK_TYPE" => "aspro_max_catalog",
          "IBLOCK_ID" => 26,
          "ELEMENT_ID" => $arParams['ELEMENTS'],
          "SHOW_COUNTER_LIST" => "Y",
          "AJAX_REQUEST" => "N",
          "ELEMENT_SORT_FIELD" => "SORT",
          "ELEMENT_SORT_ORDER" => "desc",
          "SHOW_DISCOUNT_TIME_EACH_SKU" => "N",
          "ELEMENT_SORT_FIELD2" => "sort",
          "ELEMENT_SORT_ORDER2" => "asc",
          "FILTER_NAME" => "MAX_SMART_FILTER",
          "INCLUDE_SUBSECTIONS" => "Y",
          "PAGE_ELEMENT_COUNT" => 8,
          "LINE_ELEMENT_COUNT" => 4,
          "SET_LINE_ELEMENT_COUNT" => null,
          "DISPLAY_TYPE" => "block",
          "TYPE_SKU" => "TYPE_1",
          "SET_SKU_TITLE" => null,
          "PROPERTY_CODE" => array(
            0 => "GORODA_GDE_NE_POKAZYVAT",
            1 => "HIT",
            2 => "CML2_ARTICLE",
            3 => "PROP_2104",
            4 => "KOD",
            5 => "PODBORKI",
            6 => "PROP_2033",
            7 => "TSVET_PROBIRKI",
            8 => "BRAND",
            9 => "STOIMOST_EAO",
            10 => "STOIMOST_PK",
            11 => "STOIMOST_KHAB",
            12 => "PROP_2065",
            13 => "PROP_305",
            14 => "PROP_352",
            15 => "PROP_317",
            16 => "PROP_357",
            17 => "PROP_2102",
            18 => "PROP_318",
            19 => "PROP_159",
            20 => "PROP_349",
            21 => "PROP_327",
            22 => "PROP_2052",
            23 => "PROP_370",
            24 => "PROP_336",
            25 => "PROP_2115",
            26 => "PROP_346",
            27 => "PROP_2120",
            28 => "PROP_2053",
            29 => "PROP_363",
            30 => "PROP_320",
            31 => "PROP_2089",
            32 => "PROP_325",
            33 => "PROP_2103",
            34 => "PROP_2085",
            35 => "PROP_300",
            36 => "PROP_322",
            37 => "PROP_362",
            38 => "PROP_365",
            39 => "PROP_359",
            40 => "PROP_284",
            41 => "PROP_364",
            42 => "PROP_356",
            43 => "PROP_343",
            44 => "PROP_2083",
            45 => "PROP_314",
            46 => "PROP_348",
            47 => "PROP_316",
            48 => "PROP_350",
            49 => "PROP_333",
            50 => "PROP_332",
            51 => "PROP_360",
            52 => "PROP_353",
            53 => "PROP_347",
            54 => "PROP_25",
            55 => "PROP_2114",
            56 => "PROP_301",
            57 => "PROP_2101",
            58 => "PROP_2067",
            59 => "PROP_323",
            60 => "PROP_324",
            61 => "PROP_355",
            62 => "PROP_304",
            63 => "PROP_358",
            64 => "PROP_319",
            65 => "PROP_344",
            66 => "PROP_328",
            67 => "PROP_338",
            68 => "PROP_366",
            69 => "PROP_302",
            70 => "PROP_303",
            71 => "PROP_2054",
            72 => "PROP_341",
            73 => "PROP_223",
            74 => "PROP_283",
            75 => "PROP_354",
            76 => "PROP_313",
            77 => "PROP_2066",
            78 => "PROP_329",
            79 => "PROP_342",
            80 => "PROP_367",
            81 => "PROP_2084",
            82 => "PROP_340",
            83 => "PROP_351",
            84 => "PROP_368",
            85 => "PROP_369",
            86 => "PROP_331",
            87 => "PROP_337",
            88 => "PROP_345",
            89 => "PROP_339",
            90 => "PROP_310",
            91 => "PROP_309",
            92 => "PROP_330",
            93 => "PROP_2017",
            94 => "PROP_335",
            95 => "PROP_321",
            96 => "PROP_308",
            97 => "PROP_206",
            98 => "PROP_334",
            99 => "PROP_2100",
            100 => "PROP_311",
            101 => "PROP_2132",
            102 => "SHUM",
            103 => "PROP_361",
            104 => "PROP_326",
            105 => "PROP_315",
            106 => "PROP_2091",
            107 => "PROP_2026",
            108 => "PROP_307",
            109 => "PROP_2027",
            110 => "PROP_2098",
            111 => "PROP_2122",
            112 => "PROP_24",
            113 => "PROP_2049",
            114 => "PROP_22",
            115 => "PROP_2095",
            116 => "PROP_2044",
            117 => "PROP_162",
            118 => "PROP_2055",
            119 => "PROP_2069",
            120 => "PROP_2062",
            121 => "PROP_2061",
            122 => "CML2_LINK",
            123 => "",
          ),
          "SHOW_ARTICLE_SKU" => "Y",
          "SHOW_MEASURE_WITH_RATIO" => "N",
          "MAX_SCU_COUNT_VIEW" => 20,
          "OFFERS_FIELD_CODE" => array(
            0 => "NAME",
            1 => "CML2_LINK",
            2 => "DETAIL_PAGE_URL",
            3 => "",
          ),
          "OFFERS_PROPERTY_CODE" => array(
            0 => "ARTICLE",
            1 => "MORE_PHOTO",
            2 => "SIZES2",
            3 => "VOLUME",
            4 => "SIZES3",
            5 => "SIZES4",
            6 => "SIZES5",
            7 => "SPORT",
            8 => "",
          ),
          "OFFERS_SORT_FIELD" => "sort",
          "OFFERS_SORT_ORDER" => "asc",
          "OFFERS_SORT_FIELD2" => "sort",
          "OFFERS_SORT_ORDER2" => "asc",
          "OFFER_TREE_PROPS" => array(),
          "OFFER_SHOW_PREVIEW_PICTURE_PROPS" => array(),
          "OFFERS_LIMIT" => 10,
          "SECTION_URL" => "/catalog/#SECTION_CODE_PATH#/",
          "DETAIL_URL" => "/catalog/#SECTION_CODE_PATH#/#ELEMENT_CODE#/",
          "BASKET_URL" => "/basket/",
          "ACTION_VARIABLE" => "action",
          "PRODUCT_ID_VARIABLE" => "id",
          "PRODUCT_QUANTITY_VARIABLE" => "quantity",
          "PRODUCT_PROPS_VARIABLE" => "prop",
          "MAX_GALLERY_ITEMS" => 5,
          "SHOW_GALLERY" => "N",
          "SHOW_PROPS" => "N",
          "SHOW_POPUP_PRICE" => "Y",
          "TYPE_VIEW_BASKET_BTN" => "TYPE_1",
          "TYPE_VIEW_CATALOG_LIST" => "TYPE_1",
          "SHOW_STORES_POPUP" => null,
          "SECTION_ID_VARIABLE" => "SECTION_ID",
          "SET_LAST_MODIFIED" => "Y",
          "AJAX_MODE" => "N",
          "AJAX_OPTION_JUMP" => "N",
          "AJAX_OPTION_STYLE" => "Y",
          "AJAX_OPTION_HISTORY" => "Y",
          "CACHE_TYPE" => "A",
          "CACHE_TIME" => 36000,
          "CACHE_GROUPS" => "N",
          "CACHE_FILTER" => "Y",
          "META_KEYWORDS" => "-",
          "META_DESCRIPTION" => "-",
          "BROWSER_TITLE" => "-",
          "ADD_SECTIONS_CHAIN" => "Y",
          "HIDE_NOT_AVAILABLE" => "N",
          "HIDE_NOT_AVAILABLE_OFFERS" => "N",
          "DISPLAY_COMPARE" => "N",
          "USE_FAST_VIEW" => "fast_view_1",
          "MANY_BUY_CATALOG_SECTIONS" => "Y",
          "SET_TITLE" => "Y",
          "SET_STATUS_404" => "Y",
          "SHOW_404" => "Y",
          "MESSAGE_404" => "",
          "FILE_404" => "",
          "PRICE_CODE" => array(
            0 => "BASE",
          ),
          "USE_PRICE_COUNT" => "N",
          "SHOW_PRICE_COUNT" => 1,
          "PRICE_VAT_INCLUDE" => "Y",
          "USE_PRODUCT_QUANTITY" => "N",
          "OFFERS_CART_PROPERTIES" => array(),
          "DISPLAY_TOP_PAGER" => "N",
          "DISPLAY_BOTTOM_PAGER" => "Y",
          "PAGER_TITLE" => "Товары",
          "PAGER_SHOW_ALWAYS" => "N",
          "PAGER_TEMPLATE" => "main",
          "PAGER_DESC_NUMBERING" => "N",
          "PAGER_DESC_NUMBERING_CACHE_TIME" => 36000,
          "PAGER_SHOW_ALL" => "N",
          "AJAX_OPTION_ADDITIONAL" => "",
          "ADD_CHAIN_ITEM" => "N",
          "SHOW_QUANTITY" => "Y",
          "ADD_DETAIL_TO_SLIDER" => "Y",
          "OFFER_ADD_PICT_PROP" => "MORE_PHOTO",
          "SHOW_QUANTITY_COUNT" => "Y",
          "SHOW_DISCOUNT_PERCENT_NUMBER" => "Y",
          "SHOW_DISCOUNT_PERCENT" => "Y",
          "SHOW_DISCOUNT_TIME" => "Y",
          "SHOW_ONE_CLICK_BUY" => "N",
          "SHOW_OLD_PRICE" => "Y",
          "CONVERT_CURRENCY" => "Y",
          "CURRENCY_ID" => "RUB",
          "USE_STORE" => "N",
          "MAX_AMOUNT" => 20,
          "MIN_AMOUNT" => 10,
          "USE_MIN_AMOUNT" => "N",
          "USE_ONLY_MAX_AMOUNT" => "Y",
          "DISPLAY_WISH_BUTTONS" => "N",
          "LIST_DISPLAY_POPUP_IMAGE" => "Y",
          "DEFAULT_COUNT" => 1,
          "SHOW_MEASURE" => "N",
          "SHOW_HINTS" => "Y",
          "USE_CUSTOM_RESIZE_LIST" => "N",
          "OFFER_HIDE_NAME_PROPS" => "N",
          "SHOW_SECTIONS_LIST_PREVIEW" => null,
          "SECTIONS_LIST_PREVIEW_PROPERTY" => "UF_SECTION_DESCR",
          "SHOW_SECTION_LIST_PICTURES" => "Y",
          "USE_MAIN_ELEMENT_SECTION" => "Y",
          "ADD_PROPERTIES_TO_BASKET" => "N",
          "PARTIAL_PRODUCT_PROPERTIES" => "N",
          "PRODUCT_PROPERTIES" => array(),
          "SALE_STIKER" => "SALE_TEXT",
          "STIKERS_PROP" => "HIT",
          "SHOW_RATING" => "N",
          "REVIEWS_VIEW" => 1,
          "ADD_PICT_PROP" => "MORE_PHOTO",
          "IBINHERIT_TEMPLATES" => array(),
          "FIELDS" => array(
            0 => "",
            1 => "",
          ),
          "USER_FIELDS" => array(
            0 => "",
            1 => "UF_CATALOG_ICON",
            2 => "",
          ),
          "SECTION_COUNT_ELEMENTS" => "Y",
          "UF_PRICE_CODE" => ""
        ), $component, array("HIDE_ICONS" => $isAjax)
      );?>
    </div>
<?php endif; ?>