<?php

namespace Sprint\Migration;


class MegamenuSections20251101223558 extends Version
{
    protected $author = "tafiadmin";

    protected $description = "[357317]  Изменяет разделы мега меню";

    protected $moduleVersion = "5.4.1";

    /**
     * @throws Exceptions\HelperException
     * @return bool|void
     */
    public function up()
    {
        $helper = $this->getHelperManager();

        $iblockId = $helper->Iblock()->getIblockIdIfExists(
            'aspro_max_megamenu',
            'aspro_max_catalog'
        );

        $helper->Iblock()->saveSectionsFromTree(
            $iblockId,
            array (
  0 => 
  array (
    'NAME' => 'Анализы',
    'CODE' => '',
    'SORT' => '100',
    'ACTIVE' => 'Y',
    'XML_ID' => '389',
    'PICTURE' => NULL,
    'DESCRIPTION' => '',
    'DESCRIPTION_TYPE' => 'text',
    'DETAIL_PICTURE' => NULL,
    'UF_MENU_LINK' => '/catalog/',
    'UF_CATALOG_ICON' => '0',
    'UF_MEGA_MENU_LINK' => NULL,
    'UF_CLASS' => NULL,
    'CHILDS' => 
    array (
      0 => 
      array (
        'NAME' => 'Check-up диагностика',
        'CODE' => '',
        'SORT' => '10',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'PICTURE' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'DETAIL_PICTURE' => NULL,
        'UF_MENU_LINK' => '/landings/checkup/',
        'UF_CATALOG_ICON' => NULL,
        'UF_MEGA_MENU_LINK' => NULL,
        'UF_CLASS' => NULL,
      ),
      1 => 
      array (
        'NAME' => 'Анализы по типу',
        'CODE' => '',
        'SORT' => '20',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'PICTURE' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'DETAIL_PICTURE' => NULL,
        'UF_MENU_LINK' => '/catalog/analizy_po_tipu/',
        'UF_CATALOG_ICON' => NULL,
        'UF_MEGA_MENU_LINK' => NULL,
        'UF_CLASS' => NULL,
      ),
      2 => 
      array (
        'NAME' => 'Анализы по органам и системам организма',
        'CODE' => '',
        'SORT' => '30',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'PICTURE' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'DETAIL_PICTURE' => NULL,
        'UF_MENU_LINK' => '/catalog/organy/',
        'UF_CATALOG_ICON' => NULL,
        'UF_MEGA_MENU_LINK' => NULL,
        'UF_CLASS' => NULL,
      ),
      3 => 
      array (
        'NAME' => 'Анализы по биоматериалу',
        'CODE' => '',
        'SORT' => '40',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'PICTURE' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'DETAIL_PICTURE' => NULL,
        'UF_MENU_LINK' => '/catalog/po_biomaterialu/',
        'UF_CATALOG_ICON' => NULL,
        'UF_MEGA_MENU_LINK' => NULL,
        'UF_CLASS' => NULL,
      ),
      4 => 
      array (
        'NAME' => 'Анализы по заболеваниям',
        'CODE' => '',
        'SORT' => '50',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'PICTURE' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'DETAIL_PICTURE' => NULL,
        'UF_MENU_LINK' => '/catalog/po_zabolevaniyam/',
        'UF_CATALOG_ICON' => NULL,
        'UF_MEGA_MENU_LINK' => NULL,
        'UF_CLASS' => NULL,
      ),
      5 => 
      array (
        'NAME' => 'Анализы для детей',
        'CODE' => '',
        'SORT' => '60',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'PICTURE' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'DETAIL_PICTURE' => NULL,
        'UF_MENU_LINK' => '/catalog/analizy_dlya_detey/',
        'UF_CATALOG_ICON' => NULL,
        'UF_MEGA_MENU_LINK' => NULL,
        'UF_CLASS' => NULL,
      ),
    ),
  ),
  1 => 
  array (
    'NAME' => 'Диагностика',
    'CODE' => '',
    'SORT' => '200',
    'ACTIVE' => 'Y',
    'XML_ID' => NULL,
    'PICTURE' => NULL,
    'DESCRIPTION' => '',
    'DESCRIPTION_TYPE' => 'text',
    'DETAIL_PICTURE' => NULL,
    'UF_MENU_LINK' => '#1',
    'UF_CATALOG_ICON' => NULL,
    'UF_MEGA_MENU_LINK' => NULL,
    'UF_CLASS' => NULL,
  ),
  2 => 
  array (
    'NAME' => 'Направления',
    'CODE' => '',
    'SORT' => '300',
    'ACTIVE' => 'Y',
    'XML_ID' => NULL,
    'PICTURE' => NULL,
    'DESCRIPTION' => '',
    'DESCRIPTION_TYPE' => 'text',
    'DETAIL_PICTURE' => NULL,
    'UF_MENU_LINK' => '#1',
    'UF_CATALOG_ICON' => NULL,
    'UF_MEGA_MENU_LINK' => NULL,
    'UF_CLASS' => 'direction',
    'CHILDS' => 
    array (
      0 => 
      array (
        'NAME' => 'Диагностика',
        'CODE' => '',
        'SORT' => '10',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'PICTURE' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'DETAIL_PICTURE' => NULL,
        'UF_MENU_LINK' => NULL,
        'UF_CATALOG_ICON' => NULL,
        'UF_MEGA_MENU_LINK' => NULL,
        'UF_CLASS' => NULL,
        'CHILDS' => 
        array (
          0 => 
          array (
            'NAME' => 'Лаборатория',
            'CODE' => '',
            'SORT' => '10',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'PICTURE' => NULL,
            'DESCRIPTION' => '',
            'DESCRIPTION_TYPE' => 'text',
            'DETAIL_PICTURE' => NULL,
            'UF_MENU_LINK' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_MEGA_MENU_LINK' => NULL,
            'UF_CLASS' => NULL,
          ),
          1 => 
          array (
            'NAME' => 'Рентгенография',
            'CODE' => '',
            'SORT' => '20',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'PICTURE' => NULL,
            'DESCRIPTION' => '',
            'DESCRIPTION_TYPE' => 'text',
            'DETAIL_PICTURE' => NULL,
            'UF_MENU_LINK' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_MEGA_MENU_LINK' => NULL,
            'UF_CLASS' => NULL,
          ),
          2 => 
          array (
            'NAME' => 'Маммография',
            'CODE' => '',
            'SORT' => '30',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'PICTURE' => NULL,
            'DESCRIPTION' => '',
            'DESCRIPTION_TYPE' => 'text',
            'DETAIL_PICTURE' => NULL,
            'UF_MENU_LINK' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_MEGA_MENU_LINK' => NULL,
            'UF_CLASS' => NULL,
          ),
          3 => 
          array (
            'NAME' => 'Функциональная диагностика',
            'CODE' => '',
            'SORT' => '40',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'PICTURE' => NULL,
            'DESCRIPTION' => '',
            'DESCRIPTION_TYPE' => 'text',
            'DETAIL_PICTURE' => NULL,
            'UF_MENU_LINK' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_MEGA_MENU_LINK' => NULL,
            'UF_CLASS' => NULL,
          ),
          4 => 
          array (
            'NAME' => 'УЗИ',
            'CODE' => '',
            'SORT' => '50',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'PICTURE' => NULL,
            'DESCRIPTION' => '',
            'DESCRIPTION_TYPE' => 'text',
            'DETAIL_PICTURE' => NULL,
            'UF_MENU_LINK' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_MEGA_MENU_LINK' => NULL,
            'UF_CLASS' => NULL,
          ),
        ),
      ),
      1 => 
      array (
        'NAME' => 'Лечение',
        'CODE' => '',
        'SORT' => '20',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'PICTURE' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'DETAIL_PICTURE' => NULL,
        'UF_MENU_LINK' => NULL,
        'UF_CATALOG_ICON' => NULL,
        'UF_MEGA_MENU_LINK' => NULL,
        'UF_CLASS' => NULL,
        'CHILDS' => 
        array (
          0 => 
          array (
            'NAME' => 'Гинекология',
            'CODE' => '',
            'SORT' => '10',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'PICTURE' => NULL,
            'DESCRIPTION' => '',
            'DESCRIPTION_TYPE' => 'text',
            'DETAIL_PICTURE' => NULL,
            'UF_MENU_LINK' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_MEGA_MENU_LINK' => NULL,
            'UF_CLASS' => NULL,
          ),
          1 => 
          array (
            'NAME' => 'Гинекология',
            'CODE' => '',
            'SORT' => '20',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'PICTURE' => NULL,
            'DESCRIPTION' => '',
            'DESCRIPTION_TYPE' => 'text',
            'DETAIL_PICTURE' => NULL,
            'UF_MENU_LINK' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_MEGA_MENU_LINK' => NULL,
            'UF_CLASS' => NULL,
          ),
          2 => 
          array (
            'NAME' => 'Аллергология-иммунология',
            'CODE' => '',
            'SORT' => '30',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'PICTURE' => NULL,
            'DESCRIPTION' => '',
            'DESCRIPTION_TYPE' => 'text',
            'DETAIL_PICTURE' => NULL,
            'UF_MENU_LINK' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_MEGA_MENU_LINK' => NULL,
            'UF_CLASS' => NULL,
          ),
          3 => 
          array (
            'NAME' => 'Анестезиология',
            'CODE' => '',
            'SORT' => '40',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'PICTURE' => NULL,
            'DESCRIPTION' => '',
            'DESCRIPTION_TYPE' => 'text',
            'DETAIL_PICTURE' => NULL,
            'UF_MENU_LINK' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_MEGA_MENU_LINK' => NULL,
            'UF_CLASS' => NULL,
          ),
          4 => 
          array (
            'NAME' => 'Гастроэнтерология',
            'CODE' => '',
            'SORT' => '50',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'PICTURE' => NULL,
            'DESCRIPTION' => '',
            'DESCRIPTION_TYPE' => 'text',
            'DETAIL_PICTURE' => NULL,
            'UF_MENU_LINK' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_MEGA_MENU_LINK' => NULL,
            'UF_CLASS' => NULL,
          ),
          5 => 
          array (
            'NAME' => 'Дерматовенерология',
            'CODE' => '',
            'SORT' => '60',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'PICTURE' => NULL,
            'DESCRIPTION' => '',
            'DESCRIPTION_TYPE' => 'text',
            'DETAIL_PICTURE' => NULL,
            'UF_MENU_LINK' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_MEGA_MENU_LINK' => NULL,
            'UF_CLASS' => NULL,
          ),
          6 => 
          array (
            'NAME' => 'Тест1',
            'CODE' => '',
            'SORT' => '70',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'PICTURE' => NULL,
            'DESCRIPTION' => '',
            'DESCRIPTION_TYPE' => 'text',
            'DETAIL_PICTURE' => NULL,
            'UF_MENU_LINK' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_MEGA_MENU_LINK' => NULL,
            'UF_CLASS' => NULL,
          ),
        ),
      ),
      2 => 
      array (
        'NAME' => 'Вакцинация',
        'CODE' => '',
        'SORT' => '30',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'PICTURE' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'DETAIL_PICTURE' => NULL,
        'UF_MENU_LINK' => NULL,
        'UF_CATALOG_ICON' => NULL,
        'UF_MEGA_MENU_LINK' => NULL,
        'UF_CLASS' => NULL,
        'CHILDS' => 
        array (
          0 => 
          array (
            'NAME' => 'Профилактика гриппа',
            'CODE' => '',
            'SORT' => '10',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'PICTURE' => NULL,
            'DESCRIPTION' => '',
            'DESCRIPTION_TYPE' => 'text',
            'DETAIL_PICTURE' => NULL,
            'UF_MENU_LINK' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_MEGA_MENU_LINK' => NULL,
            'UF_CLASS' => NULL,
          ),
          1 => 
          array (
            'NAME' => 'Профилактика дифтерии, столбняка, коклюша',
            'CODE' => '',
            'SORT' => '20',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'PICTURE' => NULL,
            'DESCRIPTION' => '',
            'DESCRIPTION_TYPE' => 'text',
            'DETAIL_PICTURE' => NULL,
            'UF_MENU_LINK' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_MEGA_MENU_LINK' => NULL,
            'UF_CLASS' => NULL,
          ),
          2 => 
          array (
            'NAME' => 'Профилактика вирусного гепатита В',
            'CODE' => '',
            'SORT' => '30',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'PICTURE' => NULL,
            'DESCRIPTION' => '',
            'DESCRIPTION_TYPE' => 'text',
            'DETAIL_PICTURE' => NULL,
            'UF_MENU_LINK' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_MEGA_MENU_LINK' => NULL,
            'UF_CLASS' => NULL,
          ),
          3 => 
          array (
            'NAME' => 'Профилактика кори, краснухи и паротита',
            'CODE' => '',
            'SORT' => '40',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'PICTURE' => NULL,
            'DESCRIPTION' => '',
            'DESCRIPTION_TYPE' => 'text',
            'DETAIL_PICTURE' => NULL,
            'UF_MENU_LINK' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_MEGA_MENU_LINK' => NULL,
            'UF_CLASS' => NULL,
          ),
          4 => 
          array (
            'NAME' => 'Профилактика вирусного гепатита А',
            'CODE' => '',
            'SORT' => '50',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'PICTURE' => NULL,
            'DESCRIPTION' => '',
            'DESCRIPTION_TYPE' => 'text',
            'DETAIL_PICTURE' => NULL,
            'UF_MENU_LINK' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_MEGA_MENU_LINK' => NULL,
            'UF_CLASS' => NULL,
          ),
          5 => 
          array (
            'NAME' => 'Профилактика менингококковой инфекции',
            'CODE' => '',
            'SORT' => '60',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'PICTURE' => NULL,
            'DESCRIPTION' => '',
            'DESCRIPTION_TYPE' => 'text',
            'DETAIL_PICTURE' => NULL,
            'UF_MENU_LINK' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_MEGA_MENU_LINK' => NULL,
            'UF_CLASS' => NULL,
          ),
          6 => 
          array (
            'NAME' => 'Тест2',
            'CODE' => '',
            'SORT' => '70',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'PICTURE' => NULL,
            'DESCRIPTION' => '',
            'DESCRIPTION_TYPE' => 'text',
            'DETAIL_PICTURE' => NULL,
            'UF_MENU_LINK' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_MEGA_MENU_LINK' => NULL,
            'UF_CLASS' => NULL,
          ),
        ),
      ),
    ),
  ),
  3 => 
  array (
    'NAME' => 'Врачи',
    'CODE' => '',
    'SORT' => '400',
    'ACTIVE' => 'Y',
    'XML_ID' => NULL,
    'PICTURE' => NULL,
    'DESCRIPTION' => '',
    'DESCRIPTION_TYPE' => 'text',
    'DETAIL_PICTURE' => NULL,
    'UF_MENU_LINK' => '/doctors/',
    'UF_CATALOG_ICON' => NULL,
    'UF_MEGA_MENU_LINK' => NULL,
    'UF_CLASS' => NULL,
  ),
  4 => 
  array (
    'NAME' => 'Акции',
    'CODE' => '',
    'SORT' => '500',
    'ACTIVE' => 'Y',
    'XML_ID' => NULL,
    'PICTURE' => NULL,
    'DESCRIPTION' => '',
    'DESCRIPTION_TYPE' => 'text',
    'DETAIL_PICTURE' => NULL,
    'UF_MENU_LINK' => '/sale/',
    'UF_CATALOG_ICON' => NULL,
    'UF_MEGA_MENU_LINK' => NULL,
    'UF_CLASS' => NULL,
  ),
  5 => 
  array (
    'NAME' => 'Цены',
    'CODE' => '',
    'SORT' => '600',
    'ACTIVE' => 'Y',
    'XML_ID' => NULL,
    'PICTURE' => NULL,
    'DESCRIPTION' => '',
    'DESCRIPTION_TYPE' => 'text',
    'DETAIL_PICTURE' => NULL,
    'UF_MENU_LINK' => '/price/',
    'UF_CATALOG_ICON' => NULL,
    'UF_MEGA_MENU_LINK' => NULL,
    'UF_CLASS' => NULL,
  ),
  6 => 
  array (
    'NAME' => 'Филиалы',
    'CODE' => '',
    'SORT' => '700',
    'ACTIVE' => 'Y',
    'XML_ID' => NULL,
    'PICTURE' => NULL,
    'DESCRIPTION' => '',
    'DESCRIPTION_TYPE' => 'text',
    'DETAIL_PICTURE' => NULL,
    'UF_MENU_LINK' => '/contacts/stores/',
    'UF_CATALOG_ICON' => NULL,
    'UF_MEGA_MENU_LINK' => NULL,
    'UF_CLASS' => NULL,
  ),
  7 => 
  array (
    'NAME' => 'Пациентам',
    'CODE' => '',
    'SORT' => '800',
    'ACTIVE' => 'Y',
    'XML_ID' => NULL,
    'PICTURE' => NULL,
    'DESCRIPTION' => '',
    'DESCRIPTION_TYPE' => 'text',
    'DETAIL_PICTURE' => NULL,
    'UF_MENU_LINK' => '#3',
    'UF_CATALOG_ICON' => NULL,
    'UF_MEGA_MENU_LINK' => NULL,
    'UF_CLASS' => NULL,
  ),
)        );
    }
}
